name: vajra-lm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.3
  - pytorch-cuda=12.1
  - numpy
  - pip
  - pip:
      - -e .[dev,data,serve,align,eval]
      - flash-attn==2.5.9.post1

