"""Training Summary Report Generator for Vajra Release Packages."""

import csv
import json
from pathlib import Path
from typing import Any


class TrainingReportGenerator:
    """Generates training summary reports in JSON, CSV, and Markdown formats."""

    def __init__(self, output_dir: str | Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        model_name: str,
        checkpoint_info: dict[str, Any],
        eval_metrics: dict[str, Any] | None = None,
        benchmark_metrics: dict[str, Any] | None = None,
        training_config: dict[str, Any] | None = None,
    ) -> dict[str, Path]:
        """Generate training_summary.json, training_summary.csv, and training_summary.md."""
        eval_metrics = eval_metrics or {}
        benchmark_metrics = benchmark_metrics or {}
        training_config = training_config or {}

        step = checkpoint_info.get("step", checkpoint_info.get("checkpoint_step", 0))
        tokens_seen = checkpoint_info.get("tokens_seen", 0)

        report_data = {
            "model_name": model_name,
            "best_checkpoint": checkpoint_info.get("checkpoint_filename", f"checkpoint_step_{step}.pt"),
            "checkpoint_step": step,
            "tokens_processed": tokens_seen,
            "training_duration": checkpoint_info.get("duration", "N/A"),
            "validation_loss": eval_metrics.get("validation_loss", "N/A"),
            "perplexity": eval_metrics.get("perplexity", "N/A"),
            "throughput_tokens_per_sec": benchmark_metrics.get("tokens_per_sec", "N/A"),
            "first_token_latency_ms": benchmark_metrics.get("inference_latency_first_token_ms", "N/A"),
            "distinct_1": benchmark_metrics.get("distinct_1", "N/A"),
            "dataset_name": eval_metrics.get("dataset_name", training_config.get("dataset", "FineWeb-Edu")),
            "optimizer": training_config.get("optimizer", "AdamW"),
            "learning_rate": training_config.get("learning_rate", training_config.get("lr", 3e-4)),
            "precision": training_config.get("precision", "fp32"),
        }

        # 1. Save JSON
        json_path = self.output_dir / "training_summary.json"
        with json_path.open("w", encoding="utf-8", newline="\n") as f:
            f.write(json.dumps(report_data, indent=2, sort_keys=True) + "\n")

        # 2. Save CSV
        csv_path = self.output_dir / "training_summary.csv"
        with csv_path.open("w", encoding="utf-8", newline="\n") as f:
            writer = csv.writer(f, lineterminator="\n")
            writer.writerow(["Metric", "Value"])
            for k, v in report_data.items():
                writer.writerow([k, v])

        # 3. Save MD
        md_path = self.output_dir / "training_summary.md"
        md_content = f"""# Training Summary Report for {model_name}

## Executive Summary
This document summarizes the pretraining progression, validation metrics, hardware throughput, and final checkpoint statistics for **{model_name}**.

---

## Final Statistics
| Metric | Value |
| :--- | :--- |
| **Model Name** | `{report_data['model_name']}` |
| **Best Checkpoint** | `{report_data['best_checkpoint']}` |
| **Global Training Step** | `{report_data['checkpoint_step']}` |
| **Total Tokens Processed** | `{report_data['tokens_processed']:,}` |
| **Dataset** | `{report_data['dataset_name']}` |
| **Precision** | `{report_data['precision']}` |
| **Optimizer** | `{report_data['optimizer']}` |
| **Learning Rate** | `{report_data['learning_rate']}` |

---

## Validation & Quality Performance
| Quality Telemetry | Value |
| :--- | :--- |
| **Validation Loss** | `{report_data['validation_loss']}` |
| **Perplexity** | `{report_data['perplexity']}` |
| **Distinct-1 Diversity** | `{report_data['distinct_1']}` |

---

## Benchmark Performance
| Hardware Telemetry | Value |
| :--- | :--- |
| **Throughput (Tokens/sec)** | `{report_data['throughput_tokens_per_sec']}` |
| **First Token Latency** | `{report_data['first_token_latency_ms']} ms` |

---

*Report automatically generated by Vajra Release Subsystem.*
"""
        with md_path.open("w", encoding="utf-8", newline="\n") as f:
            f.write(md_content)

        return {
            "json": json_path,
            "csv": csv_path,
            "md": md_path,
        }


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Create Training Summary Report.")
    parser.add_argument("--model-name", default="Vajra-57M")
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    generator = TrainingReportGenerator(args.output_dir)
    generator.generate(args.model_name, {"step": 250, "tokens_seen": 64000})
    print(f"Generated training summary reports at {args.output_dir}")


if __name__ == "__main__":
    main()
