"""Task Planning models and structured Plan data structures."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
import uuid
from typing import Any


class StepStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class PlanStep:
    """Represents an individual step within an execution plan."""

    step_id: str = field(default_factory=lambda: f"step_{uuid.uuid4().hex[:6]}")
    description: str = ""
    tool_name: str | None = None
    arguments: dict[str, Any] = field(default_factory=dict)
    estimated_complexity: str = "low"  # low, medium, high
    dependencies: list[str] = field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    result: Any = None
    error: str | None = None
    retry_count: int = 0
    max_retries: int = 2

    def mark_completed(self, result: Any) -> None:
        self.status = StepStatus.COMPLETED
        self.result = result

    def mark_failed(self, error: str) -> None:
        self.status = StepStatus.FAILED
        self.error = error

    def to_dict(self) -> dict[str, Any]:
        return {
            "step_id": self.step_id,
            "description": self.description,
            "tool_name": self.tool_name,
            "arguments": self.arguments,
            "complexity": self.estimated_complexity,
            "dependencies": self.dependencies,
            "status": str(self.status),
            "error": self.error,
        }


@dataclass
class Plan:
    """Structured execution plan generated by PlanningEngine."""

    objective: str
    steps: list[PlanStep] = field(default_factory=list)
    plan_id: str = field(default_factory=lambda: f"plan_{uuid.uuid4().hex[:8]}")
    is_completed: bool = False

    def get_next_pending_step(self) -> PlanStep | None:
        """Return the next executable step whose dependencies are satisfied."""
        completed_ids = {s.step_id for s in self.steps if s.status == StepStatus.COMPLETED}
        for step in self.steps:
            if step.status == StepStatus.PENDING:
                if all(dep in completed_ids for dep in step.dependencies):
                    return step
        return None

    def update_completion_status(self) -> None:
        """Check if all steps are completed or skipped."""
        self.is_completed = all(s.status in (StepStatus.COMPLETED, StepStatus.SKIPPED) for s in self.steps)

    def to_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "objective": self.objective,
            "is_completed": self.is_completed,
            "steps": [s.to_dict() for s in self.steps],
        }
